#https://raw.githubusercontent.com/EOSIO/eos/master/Docker/docker-compose-dawn3.0.yaml
version: "3"

# todo: eosio/eos-dev && --network eosdev 

services:

  nodeosd:
    image: eosio/eos #or eos-dev
    command: /bin/bash -c "\nodeos -e -p eosio \--plugin eosio::producer_plugin \--plugin eosio::history_plugin \--plugin eosio::chain_api_plugin \   --plugin eosio::history_api_plugin \ --plugin eosio::http_plugin \    -d /mnt/dev/data \  --config-dir /mnt/dev/config \    --http-server-address=0.0.0.0:8888 \ --access-control-allow-origin=* \ --contracts-console \  --http-validate-host=false"
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - $PWD/work:/work
      - $PWD/data:/mnt/dev/data
      - $PWD/config:/mnt/dev/config
    container_name: smart_nodeosd

  keosd:
    image: eosio/eos #or eos-dev
    command: /bin/bash -c "keosd --http-server-address=0.0.0.0:9876"
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - $PWD/work:/work
    # volumes:
    #   - keosd-data-volume:/opt/eosio/bin/data-dir
    container_name: smart_keosd
  